name: release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ${{ github.workspace }}/src/github.com/rajatjindal/kubectl-whoami
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
        workdir: ${{ github.workspace }}/src/github.com/rajatjindal/kubectl-whoami
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: off
        GOPATH: ${{ github.workspace }}/src/github.com/rajatjindal/kubectl-whoami
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.21
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
